matrix:
  include:
    # android
    - os: linux
      env: BUILD_TARGET=android
      language: android
      sudo: required
script:
- tools/travis-scripts/run-script.sh
before_install:
- chmod +x tools/travis-scripts/before-install.sh
- chmod +x tools/travis-scripts/run-script.sh
- tools/travis-scripts/before-install.sh

cache:
  bundler: true

notifications:
  email: false