matrix:
  include:
    # linux
    - os: linux
      env: 
        - BUILD_TARGET=linux 
        - GEN_BINDING_AND_COCOSFILE=true
      sudo: required
      language: cpp
script:
- tools/travis-scripts/run-script.sh
before_install:
- tools/travis-scripts/before-install.sh